name: "Slack Notify: Generic"
description: |
  Send a generic Slack message with optional attachment.
  Use this for custom one-off notifications (e.g. DB copy failed).
  Channel is determined by the webhook configuration.

inputs:
  webhook_url:
    description: "Slack webhook URL"
    required: true
  text:
    description: "Main message text"
    required: true
  color:
    description: "Color of the attachment (good, danger, warning, #hex, etc)"
    required: false
    default: "#439FE0"
  attachment:
    description: "Optional attachment text"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "${{ inputs.text }}",
            "attachments": [
              {
                "color": "${{ inputs.color }}",
                "text": "${{ inputs.attachment }}"
              }
            ]
          }
