name: "Slack Notify"
description: "Send Slack message on build success or failure"

inputs:
  status:
    description: "Build status: success or failure"
    required: true
  webhook_url:
    description: "Slack webhook URL"
    required: true
  repository:
    description: "Repository name"
    required: true
  branch:
    description: "Branch name"
    required: true
  commit_url:
    description: "URL to the commit"
    required: true
  commit_message:
    description: "Commit message"
    required: true

runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "${{ inputs.status == 'success' && '✅ SUCCESS' || '❌ Build FAILED' }}",
            "channel": "#build_status",
            "attachments": [
              {
                "color": "${{ inputs.status == 'success' && 'good' || 'danger' }}",
                "text": "*Repo*: ${{ inputs.repository }}\n*Branch*: ${{ inputs.branch }}\n*Commit*: <${{ inputs.commit_url }}|${{ inputs.commit_message }}"
              }
            ]
          }
