name: "Slack Notify: Build Success"
description: |
  Sends a Slack message to #build_status when a build succeeds.
  Note: This action itself does not check the branch — make sure to restrict it using
  `if: success() && github.ref == 'refs/heads/master'` in your workflow file.

inputs:
  webhook_url:
    description: "Slack webhook URL"
    required: true

runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          {            
            "text": "✅ ${{ github.repository }} built successfully! \nPlease deploy, ${{ github.actor }}.",
            "attachments": [
              {
                "color": "good",
                "text": "*Repo*: ${{ github.repository }} \n*Branch*: ${{ github.ref_name }}.\n*Commit*: <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
              }
            ]
          }
