name: "Slack Notify: Deploy"
description: |
  Sends a Slack message to #deploys when a deployment finishes.
  Use with `if: always()` and pass status as input (e.g. success, failure, cancelled).

inputs:
  webhook_url:
    description: "Slack webhook URL"
    required: true
  status:
    description: "Deployment result: success, failure, or cancelled. Use technote-space/workflow-conclusion-action@v3"
    required: true

runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          {            
            "text": "${{ inputs.status == 'success' && format('✅ {0} deployed.', github.event.repository.name) || inputs.status == 'cancelled' && format('⚪ {0} deployment was cancelled.', github.event.repository.name) || format('❌ {0} deployment failed.', github.event.repository.name) }}",
            "attachments": [
              {
                "color": "${{ inputs.status == 'success' && 'good' || inputs.status == 'cancelled' && '#aaaaaa' || 'danger' }}",
                "text": "*Run:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View on GitHub>"
              }
            ]
          }
