name: "Slack Notify: Client Release Failure"
description: |
  Sends a Slack message when a client library release fails.

inputs:
  webhook_url:
    description: "Slack webhook URL"
    required: true

runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook: ${{ inputs.webhook_url }}
        webhook-type: incoming-webhook
        payload: |
          {
            "text": "❌ ${{ github.event.repository.name }} release failed.",
            "attachments": [
              {
                "color": "danger",
                "text": "*Commit:* <${{ github.event.head_commit.url }}|${{ github.sha }}>\n*Run:* <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View on GitHub>"
              }
            ]
          }
